# Troque SEU_ORG pela "Organization Key" criada no SonarQube Cloud
sonar.organization=lucas1063
sonar.projectKey=Lucas1063_gerenciador-tarefas
sonar.projectName=Gerenciador de Tarefas

sonar.sources=src,public
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Cobertura gerada pelo Jest (npm test)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=public/**,src/server.js

# RNF-05: o pipeline espera o Quality Gate e FALHA se ele for reprovado
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
